language: node_js
node_js:
  "13"
cache:
  directories:
    "node_modules"
script:
  yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GH_TOKEN
  on:
    branch: master
